ignore:
  - 'Mini Model <minimodel@metamodel.me>'

exclude:
  - /^src\/Resources\/contao\/languages/

mapping:
  'Andreas Isaak <info@andreas-isaak.de>': 'Andreas Isaak <andy.jared@googlemail.com>'
  'Ingolf Steinhardt <info@e-spin.de>':
    - 'info@e-spin.de <info@e-spin.de>'
    - 'sandokan <info@e-spin.de>'
    - 'zonky <info@e-spin.de>'
