metamodels.attribute_rating.rate:
    path: /_metamodels/rate
    condition: "request.isXmlHttpRequest()"
    methods: ['POST']
    defaults:
      _controller: metamodels.controller.rating:ratingAction
      _scope: frontend
