services:
    metamodels.attribute_rating.factory:
        class: MetaModels\AttributeRatingBundle\Attribute\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@router'
            - '@session'
            - '@cca.dc-general.scope-matcher'
            - '%kernel.project_dir%'
            - '@request_stack'
        tags:
          - { name: metamodels.attribute_factory }

    metamodels.controller.rating:
        class: MetaModels\AttributeRatingBundle\Controller\RateAjaxController
        public: true
        arguments:
            - '@metamodels.factory'
