services:
    metamodels.attribute_rating.factory:
        class: MetaModels\Attribute\Rating\AttributeTypeFactory
        arguments:
            - '@database_connection'
            - '@router'
            - '@session'
            - '@cca.dc-general.scope-matcher'
        tags:
          - { name: metamodels.attribute_factory }

    metamodels.controller.rating:
        class: MetaModels\Attribute\Rating\Controller\RateAjaxController
        arguments:
            - '@metamodels.factory'
